### ISSUE TITLE
Add support for ESLint

### ISSUE THREAD

**Issue by ashokdey** [knaxus/native-javascript#1]
What do we need? 

- ESLint setup for the codebase
- The code standard should be **Airbnb**
- Env support for Node should be there
- The `.eslintrc` should be in JSON format

**Comment by praffn** [comment]
I have this implemented, but:

> Array prototype is read only, properties should not be added

Eslint error (no-extend-native) is of course thrown from the `forEach.js` file. Should I overwrite the airbnb rules such that native objects are extendible?

**Comment by ashokdey** [comment]
> I have this implemented, but:
> 
> > Array prototype is read only, properties should not be added
> 
> Eslint error (no-extend-native) is of course thrown from the `forEach.js` file. Should I overwrite the Airbnb rules such that native objects are extendible?

Thanks for pointing out @praffn 👍 

Considering the purpose of this project, we have to disable few rules of **AirBnB**, hence we have to override it. So you can go ahead and work accordingly.

**Comment by ashokdey** [comment]
I have assigned you this issue. ☺️
