### ISSUE TITLE
implement Array.prototype.map

### ISSUE THREAD

**Issue by praffn** [knaxus/native-javascript#16]

**Comment by praffn** [comment]
I'd like to take a shot at this

**Comment by ashokdey** [comment]
We have a PR #15 already opened for this. You can go ahead and implement and we will pick the best of both, based on various different test cases.

**Comment by ashokdey** [comment]
> _No description provided._

Also @praffn, please add description to the issue.

**Comment by praffn** [comment]
@ashokdey, I see. I will implement the two other functional array methods: `filter` and `reduce`. I already have a PR with `filter`. I will close this issue since a working implementation has been suggested

**Comment by ashokdey** [comment]
Reopening because no PR for this issue has been merged yet.

**Comment by coderwassananmol** [comment]
I would like to work on the issue.
