### ISSUE TITLE
Need a Contribution Guide

### ISSUE THREAD

**Issue by ashokdey** [knaxus/native-javascript#2]
Hello folks, I need a standard **Contribution Guide** for this repo to help people. 
Few things I want to have in it are: 

- The purpose of the project may need to break some of the **Airbnb** rules
- We need to have test cases as well

**Comment by KatFrog** [comment]
I can do this.  Do you want the standard contribution guidelines as well?  Such as always fork the code and then do a pull request to merge the changes back into the master?

**Comment by ashokdey** [comment]
> I can do this. Do you want the standard contribution guidelines as well? Such as always fork the code and then do a pull request to merge the changes back into the master?

Yes @KatFrog, I am assigning you this task!

**Comment by ashokdey** [comment]
Hello @KatFrog, please let us know the progress on this issue.

**Comment by ashokdey** [comment]
Closing due to no show.
