### ISSUE TITLE
Implement Array.prototype.flatMap()

### ISSUE THREAD

**Issue by TheSTL** [knaxus/native-javascript#20]
So you have to implement the [Array.prototype.flatMap()
](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap)

Take care of:
- ESLint guidelines
- Filename convention

**Comment by giordanna** [comment]
I'd like to try this one.

**Comment by ashokdey** [comment]
Thanks for taking interest @giordanna, I am assigning you this issue. Do mark star is you like this work.
