### ISSUE TITLE
Implement Array.prototype.sort()

### ISSUE THREAD

**Issue by TheSTL** [knaxus/native-javascript#26]
So you have to implement the [Array.prototype.sort()
](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)
You can use this article: [Time & Space Complexity of Array.sort in V8](https://blog.shovonhasan.com/time-space-complexity-of-array-sort-in-v8/)
V8 Array.sort code on github : [Array.sort](https://github.com/v8/v8/blob/master/third_party/v8/builtins/array-sort.tq)

Take care of:
- ESLint guidelines
- Filename convention

**Comment by ahmedkrmn** [comment]
Can I work on this?

**Comment by TheSTL** [comment]
Yes you can . @ahmedkrmn

**Comment by ahmedkrmn** [comment]
I will start working on this a bit later this week, so if anyone else wanna give this a try and implement it, he can do so.

**Comment by jackneer** [comment]
may I have this?

**Comment by TheSTL** [comment]
I'am closing this issue.
PR for this issue - [# 28](https://github.com/knaxus/native-javascript/pull/28)
