### ISSUE TITLE
implement String.prototype.split()

### ISSUE THREAD

**Issue by ashokdey** [knaxus/native-javascript#4]
So you have to implement the [String.prototype.split()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split)

Take care of:

- ESLint guidelines
- Filename convention

**Comment by mauricerivers** [comment]
gave this a try! let me share my code now

**Comment by terabo090** [comment]
can i also work on this?

**Comment by ashokdey** [comment]
Sure @terabo090, go ahead!

**Comment by giordanna** [comment]
Can I work on this too?

**Comment by TheSTL** [comment]
I'm closing this issue.
Merged PR is - [#35 ]
