### ISSUE TITLE
implement String.prototype.toLowerCase()

### ISSUE THREAD

**Issue by ashokdey** [knaxus/native-javascript#6]
So you have to implement the [String.prototype.toLowerCase()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase)

Take care of:
- ESLint guidelines
- Filename convention

**Comment by imravichhetri** [comment]
let me take this one.

**Comment by hiteshpr** [comment]
I would like to work on this.

**Comment by ashokdey** [comment]
To all, this issue has 2 open PRs #7 and #9, so whosoever completes it first with proper implementation will get to close this. 

Thanks

**Comment by imravichhetri** [comment]
@ashokdey Hi, I've fixed the issue. Please look into it.

**Comment by ashokdey** [comment]
@imravichhetri Please add a reference of your PR here.

**Comment by imravichhetri** [comment]
#7 Here it is

**Comment by ashokdey** [comment]
#7 closes this issue. Reopen it if you got a better solution and do refer to your PR here
