### ISSUE TITLE
implement String.prototype.toUpperCase()

### ISSUE THREAD

**Issue by ashokdey** [knaxus/native-javascript#8]
So you have to implement the [String.prototype.toUpperCase()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toUpperCase)

Take care of:
- ESLint guidelines
- Filename convention

**Comment by imravichhetri** [comment]
DId u mean toUpperCase?? And let me do this one too.

**Comment by ashokdey** [comment]
> DId u mean toUpperCase?? And let me do this one too.

Thanks, @imravichhetri I have rectified the typo and sure you can pick it up, I am assigning you this issue.

**Comment by ashokdey** [comment]
Thanks, @imravichhetri, your PR #11 closes this issue.
